### ISSUE TITLE
Error in if (attr(weighting, "Acronym") == "tf-idf") weight <- 1e-09 :    argument is of length zero

### ISSUE THREAD

**Issue by alexandrekow** [timjurka/RTextTools#4]
**tm::weightTfIdf** object has changed from version 0.5 to 0.6 

It had an attribute "Acronym" which is now "acronym" this make code using RTextTool break.
You can find people having the problem [here](https://groups.google.com/forum/#!topic/rtexttools-help/Drqr3Z897Mk) and [here](http://www.svm-tutorial.com/2014/11/svm-classify-text-r/)

This is problematic because people using R 3.1.x can't go back to tm 0.5.

It looks like [this pull request](https://github.com/timjurka/RTextTools/pull/3) correct the problem as it does not use "Acronym" anymore.

**Comment by marciovicente** [comment]
Ow, it's a old issue, but I've found this error in some page in stackoverflow. 

If you're using RStudio and get this error, yout should to use the `trace("create_matrix", edit=T)` before `create_matrix` method. Then new window will appear with the lib code, go to line 42 and change `Acronym` to `acronym`.

**Comment by alexandrekow** [comment]
Thank you.

**Comment by LoWWeek** [comment]
Hello,

How can we do this change automaticall, without change manually the code?

Can we do it with the _trace_ function and the _at_ argument?

**Comment by missAudi1994** [comment]
This solution works with me very well!
thank u very much.

**Comment by asif3051** [comment]
marciovicente Thank You very much for this solution.

**Comment by asif3051** [comment]
Hi Alexandre,

When I run the script, the errror pops up and I have to fix it manually. Is there any workaround that can apply the change of 'Acronym' to 'acronym' automatically without stopping the script execution?  Or are they any new versions of RTextTools package that has it fixed in it?

-Asif

**Comment by amkhosla** [comment]
I tried everything including devtools:gitinstall... The problem is knitr fails with the trace fix. Eventually I used trace, and copy and paste and

**Comment by amkhosla** [comment]
asiff3051 - this is what I did
1. Use trace to find function, copy and paste it into your code as create_matrix <- ... fixed ....
then:
tmpfun <- get("create_matrix", envir = asNamespace("RTextTools"))
environment(create_matrix) <- environment(tmpfun)
assignInNamespace("create_matrix", create_matrix, ns = "RTextTools")
